### ISSUE TITLE
Cypress test failing to click missing button

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1459]
## Description
When CircleCI runs, we are getting inconsistent failures from a frontend Cypress test:
```
[1]     1) open mobile menu on menu button click
[1] 
[1] 
[1]   8 passing (19s)
[1]   1 failing
[1] 
[1]   1) welcome page greeting
[1]        open mobile menu on menu button click:
[1]      Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
[1] 
[1]   > Network Error
[1] 
[1] When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
[1] 
[1] This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
[1] 
[1] https://on.cypress.io/uncaught-exception-from-application
[1]       at createError (http://localhost:3000/static/js/vendors~main.chunk.js:11565:15)
[1]       at XMLHttpRequest.handleError (http://localhost:3000/static/js/vendors~main.chunk.js:10942:14)
[1]       at XMLHttpRequest.eval (eval at makeContentWindowListener (http://localhost:3000/__cypress/runner/cypress_runner.js:173155:10), <anonymous>:4:29)
[1] 
[1] 
[1] 
[0] yarn start:ci exited with code SIGHUP
--> Sending SIGTERM to other processes..
[1] wait-on http://localhost:3000/ && yarn cy:run exited with code SIGHUP

Too long with no output (exceeded 10m0s): context deadline exceeded
```
Example runs in CI:
https://app.circleci.com/pipelines/github/raft-tech/TANF-app/5947/workflows/c394a317-cbca-4584-9c5d-211fc68cc001/jobs/13407
https://app.circleci.com/pipelines/github/raft-tech/TANF-app/5949/workflows/2fd63e5b-341b-4921-8090-5e4f61712364/jobs/13414

## Action Taken
CircleCI running test-frontend flow.

## What I did see

![image.png](https://images.zenhubusercontent.com/60abc3a8916bb9149afff73e/38d8b8e1-16d4-49fc-8cb8-46c979bdf079)
![image.png](https://images.zenhubusercontent.com/60abc3a8916bb9149afff73e/32f8c67e-0b18-4307-88d6-23c8dc3a5033)

## Other Helpful Information
After investigating with @riatzukiza , we believe this could either be a race condition with Cypress b/c it's mocking the backend and not linked up with mirage OR the vestigial button that's not visible may have been removed in #1152 but it's odd because we are only seeing this starting on November 22nd. We also upgraded our version of Cypress 14 days ago [here](https://github.com/raft-tech/TANF-app/pull/1400). There were also two javascript libraries updated but investigating them makes me believe they are unrelated [1](https://github.com/raft-tech/TANF-app/pull/1433) [2](https://github.com/raft-tech/TANF-app/pull/1435). 

Line 44 of tdrs-frontend/cypress/integration/welcome_page_greeting.spec.js
```
    cy.viewport(550, 750)

    cy.get('.usa-menu-btn').click()

    cy.get('.usa-nav').should('be.visible')
```

+ URL of the page I was on: N/A
+ Browser and version: N/A
+ Operating System: N/A
+ Is the issue repeatable?: yes
+ Has the issue occurred more than once?: yes

**Comment by abottoms-coder** [comment]
Removing the test for the button allows Cypress tests to complete:
https://app.circleci.com/pipelines/github/raft-tech/TANF-app/5958/workflows/fd967c9c-2665-4b4f-b2f6-e8374cf4e923/jobs/13441

```
  it('open mobile menu on menu button click', () => {
    cy.visit('http://localhost:3000')

    cy.viewport(550, 750)

    cy.get('.usa-menu-btn').click()

    cy.get('.usa-nav').should('be.visible')
  })
```
https://github.com/raft-tech/TANF-app/commit/8476afc21ccf2766e476812189d34ad7f0724b9b

**Comment by jtwillis92** [comment]
Somewhat related to #1427

**Comment by valcollignon** [comment]
Added ticket to "Current Sprint" and "In Progress" on boards.
CC: @abottoms-coder @riatzukiza @lfrohlich @ADPennington
