### ISSUE TITLE
As a TDP user, I'd like to see a descriptive error message page if authentication source is unavailable.

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1621]
## Description
AMS flow returned 500 error when there was an issue upstream. 

## Action Taken
@ADPennington was attempting to go through the AMS login flow on `tdp-staging-frontend.app.cloud.gov`.

## What I expected to see
We expect that she should have been directed to AMS with the accompanying data needed for redirection or an error message indicating AMS is down.

## What I did see
User experience was a minimal "500 Server Internal Error" after being redirected. Similar to this:
![image](https://user-images.githubusercontent.com/84722778/154106731-6092b528-93a7-47e0-a23e-fc060b9bec69.png)

Acceptance Criteria:
Create a list of functional outcomes that must be achieved to complete this issue:
- [ ] Exception handled gracefully, stacktrace not dumped to logs
- [ ] Error page clearly states to user that authentication service failed

Tasks:
Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue:
- [x] Grab and handle exception, return 503 status code 
- [x] Create a new template similar to our 404's index.html, text should indicate auth failure

Notes:
- Please see `tdrs-frontend/nginx/cloud.gov/locations.conf`

Cloud.gov log:
```
13:07:52.640: [APP/PROC/WEB.0] [2022-02-09 18:07:52 +0000] [570] [DEBUG] Closing connection. 
13:08:22.668: [APP/PROC/WEB.0] [2022-02-09 18:08:22 +0000] [570] [DEBUG] Closing connection. 
13:08:52.696: [APP/PROC/WEB.0] [2022-02-09 18:08:52 +0000] [569] [DEBUG] Closing connection. 
13:09:18.354: [APP/PROC/WEB.0] [2022-02-09 18:09:18 +0000] [569] [DEBUG] GET /v1/login/ams
13:09:18.751: [APP/PROC/WEB.0] ERROR Internal Server Error: /v1/login/ams
13:09:18.751: [APP/PROC/WEB.0] Traceback (most recent call last):
13:09:18.751: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
13:09:18.751: [APP/PROC/WEB.0]     response = get_response(request)
13:09:18.751: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
13:09:18.751: [APP/PROC/WEB.0]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
13:09:18.751: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
13:09:18.751: [APP/PROC/WEB.0]     return self.dispatch(request, *args, **kwargs)
13:09:18.751: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
13:09:18.751: [APP/PROC/WEB.0]     return handler(request, *args, **kwargs)
13:09:18.752: [APP/PROC/WEB.0]   File "/home/vcap/app/tdpservice/users/api/login_redirect_oidc.py", line 107, in get
13:09:18.752: [APP/PROC/WEB.0]     configuration = self.get_ams_configuration()
13:09:18.752: [APP/PROC/WEB.0]   File "/home/vcap/app/tdpservice/users/api/login_redirect_oidc.py", line 97, in get_ams_configuration
13:09:18.752: [APP/PROC/WEB.0]     data = r.json()
13:09:18.752: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/site-packages/requests/models.py", line 910, in json
13:09:18.752: [APP/PROC/WEB.0]     return complexjson.loads(self.text, **kwargs)
13:09:18.752: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/json/__init__.py", line 346, in loads
13:09:18.752: [APP/PROC/WEB.0]     return _default_decoder.decode(s)
13:09:18.752: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/json/decoder.py", line 337, in decode
13:09:18.752: [APP/PROC/WEB.0]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
13:09:18.752: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/json/decoder.py", line 355, in raw_decode
13:09:18.752: [APP/PROC/WEB.0]     raise JSONDecodeError("Expecting value", s, err.value) from None
13:09:18.752: [APP/PROC/WEB.0] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
13:09:18.752: [RTR.4] tdp-backend-staging.app.cloud.gov - [2022-02-09T18:09:18.349056981Z] "GET /v1/login/ams HTTP/1.1" 500 0 145 "https://tdp-frontend-staging.app.cloud.gov/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36" "127.0.0.1:17176" "10.10.1.26:61081" x_forwarded_for:"162.99.217.141, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"dd1c7f5d-ee15-4746-7bba-e79b884fb5e5" response_time:0.402985 gorouter_time:0.000149 app_id:"38f3b352-b485-4eb3-bcc7-1f7a100f1a5f" app_index:"0" instance_id:"8dea7ecd-036b-4907-78f2-4df1" x_cf_routererror:"-" x_b3_traceid:"7258cdcc7acba60767cc3f45fd6ff91b" x_b3_spanid:"7258cdcc7acba60767cc3f45fd6ff91b" x_b3_parentspanid:"-" b3:"7258cdcc7acba60767cc3f45fd6ff91b-7258cdcc7acba60767cc3f45fd6ff91b"
13:09:18.752: [APP/PROC/WEB.0] 10.255.8.32 - - [09/Feb/2022:18:09:18 +0000] "GET /v1/login/ams HTTP/1.1" 500 145 "https://tdp-frontend-staging.a
```
## Other Helpful Information
After reaching out to ACF AMS, we were told their services were experiencing downtime. Specifically browsing the [openid config](https://sso-stage.acf.hhs.gov/auth/realms/ACF-SSO/.well-known/openid-configuration) presented a 502 bad gateway error. We should likely wrap our code in try/catch blocks to account for scenarios like this.

+ Is the issue repeatable?:  yes
+ Has the issue occurred more than once?: yes

**Comment by abottoms-coder** [comment]
Per @riatzukiza:

```
Aaron Beavers
[2:40 PM](https://mattermost.goraft.tech/goraft/pl/7sjgtqpq77rj9mst6c19e5fe6y)
Maybe this is relavent? 
https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/

[Advanced usage of Python requests - timeouts, retries, hooks](https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/)
Learn about the advanced features the requests library hides under the hood. DRY base URLs, hooks, retry on failure, default timeouts and mocking.
If we used a requests session, and added a hook that calls raise_for_status, then we would get this behavior everywhere.
```

**Comment by robgendron** [comment]
Not exclusive to AMS, let's bring this to the front and put it back on the radar.
